services:

  postgre-db:
    image: postgres:16
    container_name: postgre
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre123
      POSTGRES_DB: b2bmatch
    ports:
      - "5433:5432"
    volumes:
      - postgre_data:/var/lib/postgresql/data
      - ../DATABASE:/sql
      - ./init:/docker-entrypoint-initdb.d

  usuarios:
    build: ./usuarios
    container_name: usuarios
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgre-db

  perfiles:
    build: ./perfiles
    container_name: perfiles
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car

  catalogo:
    build: ./catalogo
    container_name: catalogo
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
    ports:
      - "8083:8083"
    restart: unless-stopped
    depends_on:
      - postgre-db

  ofertas:
    build: ./ofertas
    container_name: ofertas
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car

  resenias:
    build: ./resenias
    container_name: resenias
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car

  notificaciones:
    build: ./notificaciones
    container_name: notificaciones
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgre123
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      JWT_SECRET: b2bmatch-super-secreto-cambiar-en-produccion-2026-minimo32car
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - usuarios
      - perfiles
      - catalogo
      - ofertas
      - resenias
      - notificaciones

volumes:
  postgre_data:
