server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  application:
    name: notificaciones
  datasource:
    url: jdbc:postgresql://postgre-db:5432/b2bmatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: notificaciones
  jpa:
    properties:
      hibernate:
        default_schema: notificaciones
    hibernate:
      ddl-auto: validate
    show-sql: true
  
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000
  internal-service-key: ${INTERNAL_SERVICE_KEY:}