server:
  port: 8081

spring:
  application:
    name: usuarios
  datasource:
    url: jdbc:postgresql://postgre-db:5432/b2bmatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: usuarios
    hibernate:
      ddl-auto: validate
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 86400000

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: 86400000