server:
  port: 8082

spring:
  application:
    name: perfiles
  datasource:
    url: jdbc:postgresql://postgre-db:5432/b2bmatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: perfiles
    hibernate:
      ddl-auto: validate
    show-sql: true
  
  jwt:
  secret: ${JWT_SECRET}
