-- Sin datos semilla de produccion para este microservicio.
--
-- Los perfiles demo (webtester / companytester) se movieron a
-- db/seed-dev/V900__demo_profiles.sql y solo se cargan cuando
-- FLYWAY_LOCATIONS incluye classpath:db/seed-dev (entorno de desarrollo).
--
-- La version V2 se conserva vacia a proposito: eliminarla romperia la
-- validacion de Flyway en bases donde ya fue aplicada.
