ALTER TABLE category ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE category ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE category ADD CONSTRAINT ck_category_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED'));

ALTER TABLE skill ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';
ALTER TABLE skill ADD COLUMN updated_at TIMESTAMP;
ALTER TABLE skill ADD CONSTRAINT ck_skill_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED', 'DELETED'));