server:
  port: 8085

spring:
  application:
    name: resenias
  datasource:
    url: jdbc:postgresql://postgre-db:5432/b2bmatch
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    properties:
      hibernate:
        default_schema: resenias
    hibernate:
      ddl-auto: validate
    show-sql: true